-   id: esss_fix_format
    description: Simple code formatter and pre-commit checker used internally by ESSS
    name: ESSS Fix Format
    entry: fix-format --commit
    language: python
    files: \.(py|pyw)$
