language: python
sudo: false
env:
  - CONDA_PY=36
  - CONDA_PY=37
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
  - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-$OS.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --system --set always_yes yes --set changeps1 no
  - conda config --system --append channels conda-forge
  - conda config --system --append channels esss
  - conda install -n base conda-devenv
install:
  - conda devenv
  - source activate esss-fix-format-py$CONDA_PY
script:
  - flake8 src tests
  - rst-lint CHANGELOG.rst README.rst
  - pytest
  - python esss_fix_format/cli.py -k .
